# This is a basic workflow to help you get started with Actions
name: Portfolio Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ portfolio ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Checkout 🛎️
      - uses: actions/checkout@v2

      # - name: Install and Build 🔧
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          projects: portfolio
          args: --baseHref="https://noseferatuwkf.github.io/fullstack-nx-workspace/"

      # - name: Deploy 🚀
      # - uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: portfolio
      #     folder: docs
