name: Portfolio Build

on:
  push:
    branches: [portfolio]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with: 
          node-version: 16
      - run: npm ci
      - run: nx build portfolio
